# Generated by Django 4.2.2 on 2023-08-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_restaurant_room_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
