# Generated by Django 4.2.2 on 2023-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_restaurant_id_room_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
