# Generated by Django 4.2.2 on 2023-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
    ]
