# Generated by Django 4.2.2 on 2023-07-11 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_api', '0001_initial'),
        ('restaurant_api', '0002_restaurant_cuisine_type_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestCount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.restaurant')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.table')),
                ('timeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.times')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
